import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/globals.css';
import { Locale } from '@/i18n.config';
import { getDictionary } from '@/lib/dictionary';
import Providers from './providers';
import { LanguageProvider } from './languageContext';
import Navbar from '@/components/Navbar';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {

  const {page} = await getDictionary(params.lang)
  const session = await getServerSession(authOptions)

  return (
    <html lang={params.lang}>
      <body className={inter.className}>
      <Providers>
        <LanguageProvider initialLanguage={params.lang}>
          <Navbar lang={params.lang} navbar={page.navbar} session={session || null}/>
          {children}
        </LanguageProvider>
      </Providers>  
      </body>
    </html>
  );
}
